### ISSUE TITLE
Timeout for long time commands

### ISSUE THREAD

**Issue by mpoma** [binarybuilds/nova-advanced-command-runner#1]
First of all: Thanks for the package, it is excellent. When commands take long time, the button with the wait animation stops and returns to being active, as if it had already finished. But the modal window is still open. However the command is still active and ends properly later. I have 2 servers and they behave the same way, at exactly 60 seconds. MAX_EXECUTION_TIME, MAX_INPUT_TIME and default_socket_timeout are in 600 secs. Any suggestion? Thanks again.

**Comment by srinathreddydudi** [comment]
@mpoma I think the issue might be because the backend is throwing a timeout exception. But behind the scenes, The commands are run in a sub process. So the command is being executed successfully. The loading animation is stopping because it stops when the request results in an exception. Can you check your log file and inspect the request and see if there is any exception being thrown from the request?

**Comment by mpoma** [comment]
Nothing in the logs.
The same problem exists when a long process is executed in a nova action.
In Actions, when I know that is a long process, I use queues. It's possible in this package?
Regards

**Comment by srinathreddydudi** [comment]
@mpoma Currently it is not possible to queue the commands. But i think it is a good feature to add. I will work on this feature and keep this issue open until this feature is implemented.

**Comment by mpoma** [comment]
Espectacular!! I dont have the skill to help you. Sorry! I'm Electronic Eng in Communications, and I used for communication hardware..... But I can help you to Test if you consider.
Regards

**Comment by srinathreddydudi** [comment]
@mpoma This is implemented in the latest release. Though this does not include any breaking changes, I tagged it as a major release so other users will have time to go through the change and implement queueing as necessary.

Please see the updated examples about implementation https://github.com/binarybuilds/nova-advanced-command-runner#examples

**Comment by mpoma** [comment]
Excelente!!!!

**Comment by mpoma** [comment]
> @mpoma This is implemented in the latest release

Im so sorry to inform you that the code have a minimal bug.
In the config I wrote

        'Rep Contador'=> [ 'run' => 'account:reports {--duedate} --should-queue', 'type' => 'info', 'group' => 'Contables', 
            'variables' => [
                [
                    'label' =>  '--duedate', // This needs to match with variable defined in the command,
                    'field' => 'select', // Allowed values (text,number,tel,select,date,email,password),
                    'options' => [
                        "--duedate='last month'" => 'Mes Pasado', 
                        "--duedate='this month'" => 'Mes Actual', 
                    ],
                    'placeholder' => 'Seleccione una Opción'
                ]
            ]
        ],
and in the execution, the command is have an error
The command "account:reports--duedate=thismonth" does not exist.
2 points
The main issue is a missing space between command and options.
A second space is lost in the variable 'this month'.
I look at the code (you make a lot of changes!!!), but I cant find the TRIM that remove the spaces.
In the previews release, the variable  "--duedate='this month'" work perfectly. 
And if I remove --should-queue, the command work perfectly.
