### ISSUE TITLE
Bug whit --should-queue whit options and arguments

### ISSUE THREAD

**Issue by mpoma** [binarybuilds/nova-advanced-command-runner#2]
> @mpoma This is implemented in the latest release

Im so sorry to inform you that the code have a minimal bug.
In the config I wrote

        'Rep Contador'=> [ 'run' => 'account:reports {--duedate} --should-queue', 'type' => 'info', 'group' => 'Contables', 
            'variables' => [
                [
                    'label' =>  '--duedate', // This needs to match with variable defined in the command,
                    'field' => 'select', // Allowed values (text,number,tel,select,date,email,password),
                    'options' => [
                        "--duedate='last month'" => 'Mes Pasado', 
                        "--duedate='this month'" => 'Mes Actual', 
                    ],
                    'placeholder' => 'Seleccione una Opción'
                ]
            ]
        ],
and in the execution, the command is have an error
The command "account:reports--duedate=thismonth" does not exist.
2 points
The main issue is a missing space between command and options.
A second space is lost in the variable 'this month'.
I look at the code (you make a lot of changes!!!), but I cant find the TRIM that remove the spaces.
In the previews release, the variable  "--duedate='this month'" work perfectly. 
And if I remove --should-queue, the command work perfectly.

_Originally posted by @mpoma in https://github.com/binarybuilds/nova-advanced-command-runner/issues/1#issuecomment-673740097_

**Comment by srinathreddydudi** [comment]
@mpoma Thanks for submiting this bug. This is fixed in `3.0.1`
