### ISSUE TITLE
Should any artisan commands be available to the tool?

### ISSUE THREAD

**Issue by 1stevengrant** [binarybuilds/nova-advanced-command-runner#8]
The commands that are outlined in the package work fine but if I try to define a call to `scout:import "App\Models\User" for example, it tells me the command isn't found.

I can of course run this command just fine from the command line normally.

**Comment by srinathreddydudi** [comment]
@1stevengrant can you share more details around how you are defining that command?

**Comment by 1stevengrant** [comment]
sure, I have the config file defined

```php
<?php

return [
    'commands' => [
        'Sync Videos' => [ 'run' => 'scout:import "App\Models\User', 'type' => 'danger', 'group' => 'Algolia' ],
    ],
    // Limit the command run history to latest 10 runs
    'history'  => 10,
    // Tool name displayed in the navigation menu
    'navigation_label' => 'Command Runner',
    // Any additional info to display on the tool page. Can contain string and html.
    'help' => '',
    // Allow running of custom artisan and bash(shell) commands
    'custom_commands' => ['artisan'],
];
```

**Comment by srinathreddydudi** [comment]
I think you are missing `'scout:import "App\Models\User'` a double quote at the end. Can you try adding that?

**Comment by 1stevengrant** [comment]
ah, sorry, yes I had that. Typo in the message above.

Here's the output

![](https://d.pr/i/uw3ikq+)

and here's the output running from the command line

![](https://d.pr/i/ekB4YX+)

**Comment by srinathreddydudi** [comment]
@1stevengrant The reason why this is not working is scout commands are registered only when the application is running in console. See https://github.com/laravel/scout/blob/9.x/src/ScoutServiceProvider.php#L43
This package will run all the artisan commands synchronously through the web request. That is the reason why the command is not defined. To fix the issue, Either run the command as a queued job by adding `--should-queue` to the command in the config, Or run it as a bash command by adding php artisan in the front and declaring it as bash command as shown below.

```php
 'commands' => [
        'Sync Videos' => [ 'run' => 'php artisan scout:import "App\Models\User', 'command_type' => 'bash', 'type' => 'danger', 'group' => 'Algolia' ],
    ],
```

**Comment by 1stevengrant** [comment]
ah, yes, of course, that makes sense :) working now. Thanks for the help. Keep up the great work.
